from urllib.parse import urlparse


TRUST_LEVEL_SCORES = {
    "high": 22,
    "medium": 14,
    "low": 2,
    "unknown": 8,
}


def normalize_domain(value: str) -> str:
    if not value:
        return ""

    parsed = urlparse(value if "://" in value else f"https://{value}")
    return parsed.netloc.lower().replace("www.", "")


def _entry(
    *,
    source_name: str,
    domain: str,
    country: str,
    region: str,
    language: str,
    source_type: str,
    base_reliability_score: int,
    transparency_signals: list[str],
    corrections_policy_known: bool,
    ownership_known: bool,
    byline_practice_known: bool,
    fact_checker_flag: bool,
    external_reference: str,
    risk_tier: str,
    review_notes: str,
    trust_level: str,
    aliases: list[str] | None = None,
    is_general_feed: bool = True,
    is_morocco_focus: bool = False,
    is_corroboration_source: bool = False,
):
    clean_domain = normalize_domain(domain)
    return {
        "source_name": source_name,
        "name": source_name,
        "domain": clean_domain,
        "country": country,
        "region": region,
        "language": language,
        "source_type": source_type,
        "base_reliability_score": int(max(0, min(100, base_reliability_score))),
        "transparency_signals": transparency_signals,
        "corrections_policy_known": corrections_policy_known,
        "ownership_known": ownership_known,
        "byline_practice_known": byline_practice_known,
        "fact_checker_flag": fact_checker_flag,
        "external_reference": external_reference,
        "risk_tier": risk_tier,
        "review_notes": review_notes,
        "trust_level": trust_level,
        "aliases": [alias.lower() for alias in (aliases or [])],
        "is_general_feed": is_general_feed,
        "is_morocco_focus": is_morocco_focus,
        "is_corroboration_source": is_corroboration_source,
    }


SOURCE_REGISTRY = [
    _entry(
        source_name="Reuters",
        domain="reuters.com",
        country="international",
        region="world",
        language="en",
        source_type="wire",
        base_reliability_score=92,
        transparency_signals=["editorial standards", "public corrections", "named authors"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=False,
        external_reference="Public newsroom standards and transparent editorial policy",
        risk_tier="low",
        review_notes="Widely used wire service with strong editorial transparency",
        trust_level="high",
        aliases=["reuters news"],
        is_corroboration_source=True,
    ),
    _entry(
        source_name="Associated Press",
        domain="apnews.com",
        country="international",
        region="world",
        language="en",
        source_type="wire",
        base_reliability_score=91,
        transparency_signals=["editorial standards", "public corrections", "named authors"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=False,
        external_reference="Public editorial standards and corrections practices",
        risk_tier="low",
        review_notes="Global wire service with strong baseline reliability",
        trust_level="high",
        aliases=["ap", "ap news", "associated press news"],
        is_corroboration_source=True,
    ),
    _entry(
        source_name="BBC",
        domain="bbc.com",
        country="uk",
        region="world",
        language="en",
        source_type="public_broadcaster",
        base_reliability_score=88,
        transparency_signals=["editorial guidelines", "ownership known", "named authors"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=False,
        external_reference="Public editorial guidelines and complaints process",
        risk_tier="low",
        review_notes="Major public broadcaster with strong transparency",
        trust_level="high",
        aliases=["bbc news"],
        is_corroboration_source=True,
    ),
    _entry(
        source_name="CNN",
        domain="cnn.com",
        country="us",
        region="world",
        language="en",
        source_type="broadcaster",
        base_reliability_score=72,
        transparency_signals=["ownership known", "editorial sections", "named correspondents"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=False,
        external_reference="Published editorial and corrections information",
        risk_tier="moderate",
        review_notes="Well-known mainstream outlet; bias is not treated as unreliability",
        trust_level="medium",
        aliases=["cnn international"],
        is_corroboration_source=True,
    ),
    _entry(
        source_name="Al Jazeera",
        domain="aljazeera.com",
        country="qa",
        region="world",
        language="en",
        source_type="broadcaster",
        base_reliability_score=76,
        transparency_signals=["ownership known", "editorial sections", "named correspondents"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=False,
        external_reference="Published editorial standards and authorship",
        risk_tier="moderate",
        review_notes="Major global newsroom with clear authorship and broad coverage",
        trust_level="medium",
        aliases=["al jazeera english"],
        is_corroboration_source=True,
    ),
    _entry(
        source_name="France 24",
        domain="france24.com",
        country="fr",
        region="world",
        language="en",
        source_type="broadcaster",
        base_reliability_score=79,
        transparency_signals=["ownership known", "authors and timestamps", "public service identity"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=False,
        external_reference="Published editorial and ownership information",
        risk_tier="low",
        review_notes="Mainstream international broadcaster with transparent identity",
        trust_level="medium",
        aliases=["france 24 english"],
        is_corroboration_source=True,
    ),
    _entry(
        source_name="The Guardian",
        domain="theguardian.com",
        country="uk",
        region="world",
        language="en",
        source_type="editorial",
        base_reliability_score=86,
        transparency_signals=["public corrections", "named authors", "ownership known"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=False,
        external_reference="Public corrections and editorial code",
        risk_tier="low",
        review_notes="Established editorial outlet with strong transparency",
        trust_level="high",
        aliases=["guardian"],
        is_general_feed=False,
        is_corroboration_source=True,
    ),
    _entry(
        source_name="The New York Times",
        domain="nytimes.com",
        country="us",
        region="world",
        language="en",
        source_type="editorial",
        base_reliability_score=87,
        transparency_signals=["public standards", "corrections page", "named authors"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=False,
        external_reference="Public standards and corrections information",
        risk_tier="low",
        review_notes="Established newsroom with strong transparency signals",
        trust_level="high",
        aliases=["new york times", "nyt"],
        is_corroboration_source=True,
    ),
    _entry(
        source_name="The Washington Post",
        domain="washingtonpost.com",
        country="us",
        region="world",
        language="en",
        source_type="editorial",
        base_reliability_score=84,
        transparency_signals=["named authors", "public standards", "ownership known"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=False,
        external_reference="Published standards and corrections",
        risk_tier="low",
        review_notes="Major editorial outlet with strong baseline reliability",
        trust_level="high",
        aliases=["washington post", "wapo"],
        is_corroboration_source=True,
    ),
    _entry(
        source_name="Sky News",
        domain="news.sky.com",
        country="uk",
        region="world",
        language="en",
        source_type="broadcaster",
        base_reliability_score=76,
        transparency_signals=["named presenters", "ownership known", "timestamped reports"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=False,
        external_reference="Published ownership and editorial information",
        risk_tier="low",
        review_notes="Mainstream broadcaster with identifiable editorial practices",
        trust_level="medium",
        aliases=["sky news"],
        is_corroboration_source=True,
    ),
    _entry(
        source_name="DW",
        domain="dw.com",
        country="de",
        region="world",
        language="en",
        source_type="public_broadcaster",
        base_reliability_score=85,
        transparency_signals=["public service identity", "named authors", "ownership known"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=False,
        external_reference="Public broadcaster standards and editorial process",
        risk_tier="low",
        review_notes="Reliable public broadcaster with clear transparency",
        trust_level="high",
        aliases=["deutsche welle"],
        is_corroboration_source=True,
    ),
    _entry(
        source_name="Bloomberg",
        domain="bloomberg.com",
        country="us",
        region="world",
        language="en",
        source_type="financial_wire",
        base_reliability_score=87,
        transparency_signals=["named reporters", "ownership known", "financial desk standards"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=False,
        external_reference="Published standards and reporter transparency",
        risk_tier="low",
        review_notes="Strong baseline on business and markets coverage",
        trust_level="high",
        is_corroboration_source=True,
    ),
    _entry(
        source_name="Financial Times",
        domain="ft.com",
        country="uk",
        region="world",
        language="en",
        source_type="financial_editorial",
        base_reliability_score=86,
        transparency_signals=["named reporters", "ownership known", "corrections information"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=False,
        external_reference="Published editorial standards and ownership information",
        risk_tier="low",
        review_notes="Established editorial outlet with strong transparency",
        trust_level="high",
        aliases=["financial times"],
        is_corroboration_source=True,
    ),
    _entry(
        source_name="NPR",
        domain="npr.org",
        country="us",
        region="world",
        language="en",
        source_type="public_media",
        base_reliability_score=85,
        transparency_signals=["editorial standards", "ownership known", "named bylines"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=False,
        external_reference="Public editorial standards and transparency notes",
        risk_tier="low",
        review_notes="Public media organization with strong editorial accountability",
        trust_level="high",
        is_corroboration_source=True,
    ),
    _entry(
        source_name="PBS News",
        domain="pbs.org",
        country="us",
        region="world",
        language="en",
        source_type="public_media",
        base_reliability_score=84,
        transparency_signals=["public service identity", "ownership known", "named authors"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=False,
        external_reference="Public editorial standards and accountability process",
        risk_tier="low",
        review_notes="Public media outlet with clear transparency",
        trust_level="high",
        aliases=["pbs", "pbs newshour"],
        is_corroboration_source=True,
    ),
    _entry(
        source_name="Agence France-Presse",
        domain="afp.com",
        country="fr",
        region="world",
        language="en",
        source_type="wire",
        base_reliability_score=89,
        transparency_signals=["editorial standards", "wire-service bylines", "ownership known"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=False,
        external_reference="Wire service standards and newsroom transparency",
        risk_tier="low",
        review_notes="Major international wire service",
        trust_level="high",
        aliases=["afp", "agence france presse"],
        is_corroboration_source=True,
    ),
    _entry(
        source_name="MAP News",
        domain="mapnews.ma",
        country="ma",
        region="ma",
        language="fr",
        source_type="public_agency",
        base_reliability_score=85,
        transparency_signals=["public institution identity", "ownership known", "dated reports"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=False,
        fact_checker_flag=False,
        external_reference="Official Moroccan public news agency identity",
        risk_tier="low",
        review_notes="Useful baseline for official Moroccan announcements",
        trust_level="high",
        is_morocco_focus=True,
        is_corroboration_source=True,
    ),
    _entry(
        source_name="Le Matin",
        domain="lematin.ma",
        country="ma",
        region="ma",
        language="fr",
        source_type="editorial",
        base_reliability_score=78,
        transparency_signals=["ownership known", "bylines", "dated articles"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=False,
        external_reference="Published newsroom identity and authorship",
        risk_tier="low",
        review_notes="Established Moroccan editorial outlet",
        trust_level="high",
        is_morocco_focus=True,
        is_corroboration_source=True,
    ),
    _entry(
        source_name="Hespress",
        domain="hespress.com",
        country="ma",
        region="ma",
        language="ar",
        source_type="editorial",
        base_reliability_score=68,
        transparency_signals=["ownership known", "article timestamps", "regular newsroom output"],
        corrections_policy_known=False,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=False,
        external_reference="Public newsroom identity",
        risk_tier="moderate",
        review_notes="Mainstream Moroccan digital outlet; treat as mixed-to-moderate baseline, not suspicious",
        trust_level="medium",
        is_morocco_focus=True,
    ),
    _entry(
        source_name="Morocco World News",
        domain="moroccoworldnews.com",
        country="ma",
        region="ma",
        language="en",
        source_type="editorial",
        base_reliability_score=69,
        transparency_signals=["named authors", "ownership known", "dated coverage"],
        corrections_policy_known=False,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=False,
        external_reference="Public newsroom identity and bylines",
        risk_tier="moderate",
        review_notes="Useful Morocco-focused editorial source with moderate prior",
        trust_level="medium",
        aliases=["mwn", "morocco world news"],
        is_morocco_focus=True,
    ),
    _entry(
        source_name="TelQuel",
        domain="telquel.ma",
        country="ma",
        region="ma",
        language="fr",
        source_type="editorial",
        base_reliability_score=70,
        transparency_signals=["ownership known", "dated coverage", "bylines"],
        corrections_policy_known=False,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=False,
        external_reference="Public editorial identity and authorship",
        risk_tier="moderate",
        review_notes="Known Moroccan editorial outlet with moderate baseline reliability",
        trust_level="medium",
        is_morocco_focus=True,
    ),
    _entry(
        source_name="SNRT News",
        domain="snrtnews.com",
        country="ma",
        region="ma",
        language="fr",
        source_type="public_broadcaster",
        base_reliability_score=79,
        transparency_signals=["public broadcaster identity", "ownership known", "dated coverage"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=False,
        fact_checker_flag=False,
        external_reference="Public broadcaster editorial identity",
        risk_tier="low",
        review_notes="Useful official broadcaster baseline for Morocco coverage",
        trust_level="high",
        aliases=["snrt"],
        is_morocco_focus=True,
        is_corroboration_source=True,
    ),
    _entry(
        source_name="Full Fact",
        domain="fullfact.org",
        country="uk",
        region="world",
        language="en",
        source_type="fact_checker",
        base_reliability_score=90,
        transparency_signals=["methodology page", "corrections policy", "named researchers"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=True,
        external_reference="Public methodology and corrections information",
        risk_tier="low",
        review_notes="Independent fact-checking organization",
        trust_level="high",
        aliases=["full fact"],
        is_general_feed=False,
        is_corroboration_source=True,
    ),
    _entry(
        source_name="Africa Check",
        domain="africacheck.org",
        country="za",
        region="world",
        language="en",
        source_type="fact_checker",
        base_reliability_score=89,
        transparency_signals=["methodology page", "ownership known", "named researchers"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=True,
        external_reference="Public methodology and accountability notes",
        risk_tier="low",
        review_notes="Independent fact-checking organization relevant to the region",
        trust_level="high",
        aliases=["africa check"],
        is_general_feed=False,
        is_corroboration_source=True,
    ),
    _entry(
        source_name="PolitiFact",
        domain="politifact.com",
        country="us",
        region="world",
        language="en",
        source_type="fact_checker",
        base_reliability_score=87,
        transparency_signals=["methodology page", "named reporters", "corrections notes"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=True,
        external_reference="Public fact-checking methodology",
        risk_tier="low",
        review_notes="Specialized fact-checking organization",
        trust_level="high",
        aliases=["politi fact"],
        is_general_feed=False,
        is_corroboration_source=True,
    ),
    _entry(
        source_name="Snopes",
        domain="snopes.com",
        country="us",
        region="world",
        language="en",
        source_type="fact_checker",
        base_reliability_score=84,
        transparency_signals=["methodology page", "corrections known", "named writers"],
        corrections_policy_known=True,
        ownership_known=True,
        byline_practice_known=True,
        fact_checker_flag=True,
        external_reference="Published methodology and accountability notes",
        risk_tier="low",
        review_notes="Independent fact-checking site with established methodology",
        trust_level="high",
        is_general_feed=False,
        is_corroboration_source=True,
    ),
    _entry(
        source_name="InfoWars",
        domain="infowars.com",
        country="us",
        region="world",
        language="en",
        source_type="high_risk",
        base_reliability_score=12,
        transparency_signals=[],
        corrections_policy_known=False,
        ownership_known=True,
        byline_practice_known=False,
        fact_checker_flag=False,
        external_reference="Repeated misinformation concerns and weak editorial safeguards",
        risk_tier="high",
        review_notes="Known high-risk source; strong negative prior is justified",
        trust_level="low",
        is_general_feed=False,
    ),
    _entry(
        source_name="Natural News",
        domain="naturalnews.com",
        country="us",
        region="world",
        language="en",
        source_type="high_risk",
        base_reliability_score=16,
        transparency_signals=[],
        corrections_policy_known=False,
        ownership_known=True,
        byline_practice_known=False,
        fact_checker_flag=False,
        external_reference="Weak editorial safeguards and repeated misinformation concerns",
        risk_tier="high",
        review_notes="Known high-risk source; negative prior is justified",
        trust_level="low",
        aliases=["natural news"],
        is_general_feed=False,
    ),
    _entry(
        source_name="Before It's News",
        domain="beforeitsnews.com",
        country="us",
        region="world",
        language="en",
        source_type="high_risk",
        base_reliability_score=10,
        transparency_signals=[],
        corrections_policy_known=False,
        ownership_known=False,
        byline_practice_known=False,
        fact_checker_flag=False,
        external_reference="Open conspiracy-oriented publishing model with weak accountability",
        risk_tier="high",
        review_notes="Known high-risk source; strong negative prior is justified",
        trust_level="low",
        aliases=["before its news"],
        is_general_feed=False,
    ),
]
def trust_level_score(trust_level: str) -> int:
    return TRUST_LEVEL_SCORES.get(trust_level or "unknown", TRUST_LEVEL_SCORES["unknown"])


def _match_domain(candidate_domain: str, registry_domain: str) -> bool:
    return candidate_domain == registry_domain or candidate_domain.endswith(f".{registry_domain}")


def _build_unknown_profile(url: str = "", source_name: str = "") -> dict:
    domain = normalize_domain(url)
    region = "ma" if any(token in domain for token in [".ma", "morocco"]) else "world"

    return {
        "source_name": source_name or domain or "Unknown source",
        "name": source_name or domain or "Unknown source",
        "domain": domain,
        "country": "unknown",
        "region": region,
        "language": "unknown",
        "source_type": "unknown",
        "base_reliability_score": 54,
        "transparency_signals": [],
        "corrections_policy_known": False,
        "ownership_known": False,
        "byline_practice_known": False,
        "fact_checker_flag": False,
        "external_reference": "No structured registry entry yet",
        "risk_tier": "moderate",
        "review_notes": "Unknown source receives a neutral-low prior, not a suspicious verdict.",
        "trust_level": "unknown",
        "aliases": [],
        "is_general_feed": True,
        "is_morocco_focus": region == "ma",
        "is_corroboration_source": False,
    }


def get_source_profile(url: str = "", source_name: str = "") -> dict:
    domain = normalize_domain(url)
    lowered_name = (source_name or "").strip().lower()

    for item in SOURCE_REGISTRY:
        if domain and _match_domain(domain, item["domain"]):
            return dict(item)

    for item in SOURCE_REGISTRY:
        if lowered_name and (
            lowered_name == item["source_name"].lower() or lowered_name in item.get("aliases", [])
        ):
            return dict(item)

    return _build_unknown_profile(url=url, source_name=source_name)
